name: pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9","3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --with dev
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_from_name
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_data_logic
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_bg_linear_model
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_create_threshold_aperture
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_create_prf_aperture
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_create_ellipse_aperture
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_pixel_quality
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_make_tpf
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_to_lightcurve_aperture
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_to_lightcurve_psf
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_calculate_TESSmag
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_make_lc
    - name: Test with pytest
      run: |
        poetry run pytest tests/test_movingtpf.py::test_comet

